kubectl create ns node-namespace-nautilus

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment-nautilus
  namespace: node-namespace-nautilus
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: node-container-nautilus
        image: gcr.io/kodekloud/centos-ssh-enabled:node
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-service-nautilus
  namespace: node-namespace-nautilus
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30012
